#!/usr/bin/env bash

if [ $# -ne 1 ]; then
  >&2 echo "Usage: $0 <author>"
  exit 1
fi

AUTHOR=$1
AUTHOR_NAME=$(echo $AUTHOR | perl -wlne '/^(.*)\s*<.*>$/ and print $1')
AUTHOR_EMAIL=$(echo $AUTHOR | perl -wlne '/^.*\s*<(.*)>$/ and print $1')

git filter-branch --commit-filter "
  export GIT_AUTHOR_NAME=$AUTHOR_NAME;
  export GIT_COMMITER_NAME=$AUTHOR_NAME;
  export GIT_AUTHOR_EMAIL=$AUTHOR_EMAIL;
  export GIT_COMMITER_EMAIL=$AUTHOR_EMAIL;
  git commit-tree "'$@'

echo "$AUTHOR_NAME is now the author of ALL the commits on the current branch."
echo "Congratulations!"
